# Server Configuration
server.port=8082
server.servlet.context-path=/api

# Database Configuration
spring.datasource.url=jdbc:mysql://monorail.proxy.rlwy.net:36412/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=SnehaSD@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=greenTraceSecretKey2024ForJWTTokenGenerationMustBeAtLeast32CharactersLong
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Spoonacular API
spoonacular.api.key=8c2703ecb120483b8606fe6091bdc34d
spoonacular.api.url=https://api.spoonacular.com

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.greentrace=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**


